server:
  port: 9099

app:
  id: 602518344108609536  #项目ID

spring:
  # datasource 数据源配置内容，对应 DataSourceProperties 配置属性类
  datasource:
    url: jdbc:mysql://8.8.8.8:9088/s3eccis?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 88888888
    # HikariCP 自定义配置，对应 HikariConfig 配置属性类
    hikari:
      minimum-idle: 1 # 池中维护的最小空闲连接数，默认为 10 个。
      maximum-pool-size: 10 # 池中最大连接数，包括闲置和使用中的连接，默认为 10 个。

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

#MQTT配置信息
mqtt:
  url:
  username:
  password:
  client-id: 602518344108609536
  id: 1
  timeout: 120
  keep-alive: 20
  qos: 1,1,1,1,1
  completion-timeout: 3000
  topics: /8cce4e513ef0/subcribe,v3/sub/HA/WSE2/A08B30,v3/sub/HA/WPS2/4E68C8,v3/sub/HA/WPS2/A2227C,v3/sub/HA/WPS2/A15F90


swagger:
  version: DEV


